# Generated by Django 6.1.1 on 2026-09-25 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('time', models.TimeField(verbose_name='Час проведення')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведення')),
                ('place', models.CharField(max_length=300, verbose_name='Місце проведення')),
                ('type', models.CharField(choices=[('meeting', 'Онлайн зустріч'), ('conference', 'Конференція'), ('presentation', 'Презентація')], max_length=15, verbose_name='Тип події')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
        ),
    ]
