# Generated by Django 6.1.1 on 2026-09-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='materials/')),
                ('you_tube_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
