# Generated by Django 6.1.1 on 2026-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, upload_to='materials/images/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/'),
        ),
    ]
