# Generated by Django 5.0.6 on 2026-09-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Назва")),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активне")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Створено")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Оновлено")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_polls", to=settings.AUTH_USER_MODEL, verbose_name="Автор")),
            ],
            options={"verbose_name": "Голосування", "verbose_name_plural": "Голосування", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=250, verbose_name="Варіант")),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="voting.poll")),
            ],
            options={"verbose_name": "Варіант відповіді", "verbose_name_plural": "Варіанти відповідей", "ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("option", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="voting.polloption")),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="voting.poll")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Голос", "verbose_name_plural": "Голоси"},
        ),
        migrations.AddConstraint(model_name="vote", constraint=models.UniqueConstraint(fields=("poll", "user"), name="one_vote_per_user_per_poll")),
    ]
