# Generated by Django 6.0.6 on 2026-09-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_comments_options_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_time',
            field=models.CharField(choices=[('Newest', 'Найновіші'), ('Oldest', 'Найстаріші')], default='Newest', max_length=10, verbose_name='Сортування за часом створення'),
        ),
    ]
